### ISSUE TITLE
API endpoints support

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/rss-reader-angular#10]
This issue will be the official tracker for API endpoints support (meant for the app but will be available for public use).
This issue will be also updated accordingly if there'll be progress reports/new API endpoints.

# `GET` https://example.com/api/news
Gets the latest news.

## Parameters:
Name | Description
---|---
`topic` | A topic (`technology`, `news`, etc.)

---

# `GET` https://example.com/api/notifications
Gets the notifications of unread news article(s) that he/she hasn't read.
**:warning:  Requires the user to be authenticated before continuing**

## Parameters:
Name | Description
---|---
`userID` | The user's ID

---

# `GET` https://example.com/api/readlater
Gets all article(s) that he/she has marked as _read later_.
**:warning:  Requires the user to be authenticated before continuing**

## Parameters:
Name | Description
---|---
`userID` | The user's ID
# `POST` https://example.com/api/readlater
When posted, it will be added to the list of read laters that he/she has.
**:warning:  Requires the user to be authenticated before continuing**

## Parameters:
Name | Description
---|---
`post` | The post to be added to read later
`userID` | Where to save the post to (aka the user's ID)

# `DELETE` https://example.com/api/readlater
Deletes the specified read later.
**:warning:  Requires the user to be authenticated before continuing**
## Parameters:
Name | Description
---|---
`postID` | The ID of the post to be deleted
# TODO
- [ ] Implement auth **(required to prevent others from accessing confidential stuff)**
- [ ] Figure out how to allow parameters
- [ ] Use Heroku for API endpoint support
- [ ] Read documentation on Heroku
- [ ] MongoDB/Alternate database service
- [ ] Update links above with URL of Heroku app
- [ ] Figure out which branch to place Heroku in
- [ ] Read up on Express.js

**Comment by EdricChan03** [comment]
Abandoned as it wasn't really worked on.
